// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	dto "github.com/iqbalnzls/watchcommerce/src/dto"
	mock "github.com/stretchr/testify/mock"
)

// BrandServiceIFaceMock is an autogenerated mock type for the BrandServiceIFace type
type BrandServiceIFaceMock struct {
	mock.Mock
}

// Save provides a mock function with given fields: req
func (_m *BrandServiceIFaceMock) Save(req *dto.CreateBrandRequest) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.CreateBrandRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
