// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Brand struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Product struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	BrandID  int    `json:"brandID"`
	Price    int    `json:"price"`
	Quantity int    `json:"quantity"`
}

type Query struct {
}
