// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Brand struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Product struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	BrandName string `json:"brandName"`
	Price     int    `json:"price"`
	Quantity  int    `json:"quantity"`
}

type ProductInput struct {
	BrandID  int    `json:"brandId"`
	Name     string `json:"name"`
	Price    int    `json:"price"`
	Quantity int    `json:"quantity"`
}

type Query struct {
}
