// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/iqbalnzls/watchcommerce/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// BrandRepositoryIFaceMock is an autogenerated mock type for the BrandRepositoryIFace type
type BrandRepositoryIFaceMock struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *BrandRepositoryIFaceMock) Save(_a0 *domain.Brand) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Brand) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBrandRepositoryIFaceMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewBrandRepositoryIFaceMock creates a new instance of BrandRepositoryIFaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBrandRepositoryIFaceMock(t mockConstructorTestingTNewBrandRepositoryIFaceMock) *BrandRepositoryIFaceMock {
	mock := &BrandRepositoryIFaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
