// Code generated by mockery v2.13.0. DO NOT EDIT.

package mocks

import (
	brand "github.com/iqbalnzls/watchcommerce/src/domain/brand"
	mock "github.com/stretchr/testify/mock"
)

// BrandRepositoryIFaceMock is an autogenerated mock type for the BrandRepositoryIFace type
type BrandRepositoryIFaceMock struct {
	mock.Mock
}

// Save provides a mock function with given fields: domain
func (_m *BrandRepositoryIFaceMock) Save(domain *brand.Brand) error {
	ret := _m.Called(domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*brand.Brand) error); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
