// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	order "github.com/iqbalnzls/watchcommerce/src/domain/order"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepositoryIFaceMock is an autogenerated mock type for the OrderRepositoryIFace type
type OrderRepositoryIFaceMock struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *OrderRepositoryIFaceMock) Get(id int64) (*order.Order, error) {
	ret := _m.Called(id)

	var r0 *order.Order
	if rf, ok := ret.Get(0).(func(int64) *order.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: domain
func (_m *OrderRepositoryIFaceMock) Save(domain *order.Order) (int64, error) {
	ret := _m.Called(domain)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*order.Order) int64); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*order.Order) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
