// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	order_details "github.com/iqbalnzls/watchcommerce/src/domain/order_details"
	mock "github.com/stretchr/testify/mock"
)

// OrderDetailsRepositoryIFaceMock is an autogenerated mock type for the OrderDetailsRepositoryIFace type
type OrderDetailsRepositoryIFaceMock struct {
	mock.Mock
}

// GetByOrderID provides a mock function with given fields: orderID
func (_m *OrderDetailsRepositoryIFaceMock) GetByOrderID(orderID int64) ([]*order_details.OrderDetails, error) {
	ret := _m.Called(orderID)

	var r0 []*order_details.OrderDetails
	if rf, ok := ret.Get(0).(func(int64) []*order_details.OrderDetails); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*order_details.OrderDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBulk provides a mock function with given fields: orderID, domains
func (_m *OrderDetailsRepositoryIFaceMock) SaveBulk(orderID int64, domains []order_details.OrderDetails) error {
	ret := _m.Called(orderID, domains)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, []order_details.OrderDetails) error); ok {
		r0 = rf(orderID, domains)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
