// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	dto "github.com/iqbalnzls/watchcommerce/src/dto"
	app_context "github.com/iqbalnzls/watchcommerce/src/shared/app_context"

	mock "github.com/stretchr/testify/mock"
)

// ProductServiceIFaceMock is an autogenerated mock type for the ServiceIFace type
type ProductServiceIFaceMock struct {
	mock.Mock
}

type ProductServiceIFaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductServiceIFaceMock) EXPECT() *ProductServiceIFaceMock_Expecter {
	return &ProductServiceIFaceMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: appCtx, req
func (_m *ProductServiceIFaceMock) Get(appCtx *app_context.AppContext, req *dto.GetProductRequest) (dto.GetProductResponse, error) {
	ret := _m.Called(appCtx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *dto.GetProductRequest) (dto.GetProductResponse, error)); ok {
		return rf(appCtx, req)
	}
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *dto.GetProductRequest) dto.GetProductResponse); ok {
		r0 = rf(appCtx, req)
	} else {
		r0 = ret.Get(0).(dto.GetProductResponse)
	}

	if rf, ok := ret.Get(1).(func(*app_context.AppContext, *dto.GetProductRequest) error); ok {
		r1 = rf(appCtx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductServiceIFaceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProductServiceIFaceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - appCtx *app_context.AppContext
//   - req *dto.GetProductRequest
func (_e *ProductServiceIFaceMock_Expecter) Get(appCtx interface{}, req interface{}) *ProductServiceIFaceMock_Get_Call {
	return &ProductServiceIFaceMock_Get_Call{Call: _e.mock.On("Get", appCtx, req)}
}

func (_c *ProductServiceIFaceMock_Get_Call) Run(run func(appCtx *app_context.AppContext, req *dto.GetProductRequest)) *ProductServiceIFaceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app_context.AppContext), args[1].(*dto.GetProductRequest))
	})
	return _c
}

func (_c *ProductServiceIFaceMock_Get_Call) Return(resp dto.GetProductResponse, err error) *ProductServiceIFaceMock_Get_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *ProductServiceIFaceMock_Get_Call) RunAndReturn(run func(*app_context.AppContext, *dto.GetProductRequest) (dto.GetProductResponse, error)) *ProductServiceIFaceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBrandID provides a mock function with given fields: appCtx, req
func (_m *ProductServiceIFaceMock) GetByBrandID(appCtx *app_context.AppContext, req *dto.GetProductByBrandIDRequest) ([]dto.GetProductResponse, error) {
	ret := _m.Called(appCtx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetByBrandID")
	}

	var r0 []dto.GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *dto.GetProductByBrandIDRequest) ([]dto.GetProductResponse, error)); ok {
		return rf(appCtx, req)
	}
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *dto.GetProductByBrandIDRequest) []dto.GetProductResponse); ok {
		r0 = rf(appCtx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GetProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*app_context.AppContext, *dto.GetProductByBrandIDRequest) error); ok {
		r1 = rf(appCtx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductServiceIFaceMock_GetByBrandID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBrandID'
type ProductServiceIFaceMock_GetByBrandID_Call struct {
	*mock.Call
}

// GetByBrandID is a helper method to define mock.On call
//   - appCtx *app_context.AppContext
//   - req *dto.GetProductByBrandIDRequest
func (_e *ProductServiceIFaceMock_Expecter) GetByBrandID(appCtx interface{}, req interface{}) *ProductServiceIFaceMock_GetByBrandID_Call {
	return &ProductServiceIFaceMock_GetByBrandID_Call{Call: _e.mock.On("GetByBrandID", appCtx, req)}
}

func (_c *ProductServiceIFaceMock_GetByBrandID_Call) Run(run func(appCtx *app_context.AppContext, req *dto.GetProductByBrandIDRequest)) *ProductServiceIFaceMock_GetByBrandID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app_context.AppContext), args[1].(*dto.GetProductByBrandIDRequest))
	})
	return _c
}

func (_c *ProductServiceIFaceMock_GetByBrandID_Call) Return(resp []dto.GetProductResponse, err error) *ProductServiceIFaceMock_GetByBrandID_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *ProductServiceIFaceMock_GetByBrandID_Call) RunAndReturn(run func(*app_context.AppContext, *dto.GetProductByBrandIDRequest) ([]dto.GetProductResponse, error)) *ProductServiceIFaceMock_GetByBrandID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: appCtx, req
func (_m *ProductServiceIFaceMock) Save(appCtx *app_context.AppContext, req *dto.CreateProductRequest) error {
	ret := _m.Called(appCtx, req)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *dto.CreateProductRequest) error); ok {
		r0 = rf(appCtx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductServiceIFaceMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ProductServiceIFaceMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - appCtx *app_context.AppContext
//   - req *dto.CreateProductRequest
func (_e *ProductServiceIFaceMock_Expecter) Save(appCtx interface{}, req interface{}) *ProductServiceIFaceMock_Save_Call {
	return &ProductServiceIFaceMock_Save_Call{Call: _e.mock.On("Save", appCtx, req)}
}

func (_c *ProductServiceIFaceMock_Save_Call) Run(run func(appCtx *app_context.AppContext, req *dto.CreateProductRequest)) *ProductServiceIFaceMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app_context.AppContext), args[1].(*dto.CreateProductRequest))
	})
	return _c
}

func (_c *ProductServiceIFaceMock_Save_Call) Return(err error) *ProductServiceIFaceMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductServiceIFaceMock_Save_Call) RunAndReturn(run func(*app_context.AppContext, *dto.CreateProductRequest) error) *ProductServiceIFaceMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductServiceIFaceMock creates a new instance of ProductServiceIFaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceIFaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceIFaceMock {
	mock := &ProductServiceIFaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
