package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/iqbalnzls/watchcommerce/src/delivery/graph/model"
	"github.com/iqbalnzls/watchcommerce/src/dto"
)

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id int) (resp *model.Product, err error) {
	req := &dto.GetProductRequest{
		ProductID: int64(id),
	}

	if err = r.Resolver.v.Validate(req); err != nil {
		return
	}

	data, err := r.Resolver.productService.Get(req)
	if err != nil {
		return
	}

	resp = toProduct(data)
	return
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
