// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	app_context "github.com/iqbalnzls/watchcommerce/src/shared/app_context"

	domain "github.com/iqbalnzls/watchcommerce/src/domain"

	mock "github.com/stretchr/testify/mock"
)

// BrandRepositoryIFaceMock is an autogenerated mock type for the RepositoryIFace type
type BrandRepositoryIFaceMock struct {
	mock.Mock
}

type BrandRepositoryIFaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BrandRepositoryIFaceMock) EXPECT() *BrandRepositoryIFaceMock_Expecter {
	return &BrandRepositoryIFaceMock_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: appCtx, _a1
func (_m *BrandRepositoryIFaceMock) Save(appCtx *app_context.AppContext, _a1 *domain.Brand) error {
	ret := _m.Called(appCtx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*app_context.AppContext, *domain.Brand) error); ok {
		r0 = rf(appCtx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BrandRepositoryIFaceMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type BrandRepositoryIFaceMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - appCtx *app_context.AppContext
//   - _a1 *domain.Brand
func (_e *BrandRepositoryIFaceMock_Expecter) Save(appCtx interface{}, _a1 interface{}) *BrandRepositoryIFaceMock_Save_Call {
	return &BrandRepositoryIFaceMock_Save_Call{Call: _e.mock.On("Save", appCtx, _a1)}
}

func (_c *BrandRepositoryIFaceMock_Save_Call) Run(run func(appCtx *app_context.AppContext, _a1 *domain.Brand)) *BrandRepositoryIFaceMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app_context.AppContext), args[1].(*domain.Brand))
	})
	return _c
}

func (_c *BrandRepositoryIFaceMock_Save_Call) Return(err error) *BrandRepositoryIFaceMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrandRepositoryIFaceMock_Save_Call) RunAndReturn(run func(*app_context.AppContext, *domain.Brand) error) *BrandRepositoryIFaceMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewBrandRepositoryIFaceMock creates a new instance of BrandRepositoryIFaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrandRepositoryIFaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrandRepositoryIFaceMock {
	mock := &BrandRepositoryIFaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
