// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/iqbalnzls/watchcommerce/src/dto"
	mock "github.com/stretchr/testify/mock"
)

// OrderServiceIFaceMock is an autogenerated mock type for the OrderServiceIFace type
type OrderServiceIFaceMock struct {
	mock.Mock
}

// Get provides a mock function with given fields: req
func (_m *OrderServiceIFaceMock) Get(req *dto.GetOrderRequest) (dto.GetOrderResponse, error) {
	ret := _m.Called(req)

	var r0 dto.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.GetOrderRequest) (dto.GetOrderResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*dto.GetOrderRequest) dto.GetOrderResponse); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(dto.GetOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(*dto.GetOrderRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: req
func (_m *OrderServiceIFaceMock) Save(req *dto.CreateOrderRequest) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.CreateOrderRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOrderServiceIFaceMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderServiceIFaceMock creates a new instance of OrderServiceIFaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderServiceIFaceMock(t mockConstructorTestingTNewOrderServiceIFaceMock) *OrderServiceIFaceMock {
	mock := &OrderServiceIFaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
